apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx # 名前をつける
spec:
  selector: # どのPodを起動するか
    matchLabels:
      app: nginx
  replicas: 3 # Podの数
  template: # 作成されるPodのテンプレート
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80