apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx # 名前をつける
spec:
  selector: # どのPodを起動するか
    matchLabels:
      app: nginx
  replicas: 3 # Podの数
  template: # 作成されるPodのテンプレート
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: text-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: nginx